# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77999c20f2696cb69776915ab5a00669688f9d42af7aebdbae20664e2043f0f04cfa794001b292b2ee32d0546df3ac4437df35de4872138707b0c830a848ce15

test:
  secret_key_base: a1379d1ccf31ec93c95bab1c4028a488d9e784643c507d8bd8374c6fb7d87972874e82f34d306a48d6f289f8f416f84b40dc02a176bc1879ec6b76e28e22e897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
